CXX = gcc
CFLAGS = -Wall -Wextra
.PHONY: all countdown clean
all:clean
	$(CXX) $(CFLAGS) -o main main.c
	$(CXX) $(CFLAGS) -o main2 main2.
	$(CXX) $(CFLAGS) -o santa santa.c
santa:clean
	$(CXX) $(CFLAGS) -o santa santa.c
clean:
	rm -f main santa main2